version: "3"

services:

  redis:
    image: redis:7
    container_name: redis-stream
    ports:
      - "6379:6379"

  redis-stream-app:
    build: .
    container_name: job-queue-service
    ports:
      - "8080:8080"
    depends_on:
      - redis